name: "Debug OWASP Detection"

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  log-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code scanning alerts
        id: fetch_alerts
        uses: actions/github-script@v6
        with:
          script: |
            const alerts = await github.request('GET /repos/{owner}/{repo}/code-scanning/alerts', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100  // Fetch up to 100 alerts per page
            });

            // Log the full alert data for each alert
            alerts.data.forEach(alert => {
              console.log("Full Alert Data:", JSON.stringify(alert, null, 2));
            });

            return alerts.data;
