name: "Detect and Annotate OWASP Alerts"

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "0 0 * * *"  # Run daily, adjust based on your needs

jobs:
  detect-and-annotate-owasp:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code scanning alerts
        id: fetch_alerts
        uses: actions/github-script@v6
        with:
          script: |
            const alerts = await github.request('GET /repos/{owner}/{repo}/code-scanning/alerts', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });

            // Filter for OWASP-related alerts
            let owaspRelatedAlerts = alerts.data.filter(alert =>
              // Check for OWASP references in the alert description
              alert.rule.description.toLowerCase().includes("owasp") ||
              // Check for common OWASP-related CWE IDs
              alert.cwe?.id === "CWE-1333" ||  // Regular expression DoS (ReDoS)
              alert.cwe?.id === "CWE-400"  ||  // Uncontrolled Resource Consumption (CWE-400)
              alert.cwe?.id === "CWE-730"  ||  // OWASP-related
              // Additional OWASP Top 10-related keywords
              alert.rule.description.toLowerCase().includes("injection") ||
              alert.rule.description.toLowerCase().includes("ssrf") ||
              alert.rule.description.toLowerCase().includes("xss") ||
              alert.rule.description.toLowerCase().includes("access control") ||
              alert.rule.description.toLowerCase().includes("authentication") ||
              alert.rule.description.toLowerCase().includes("misconfiguration")
            );

            if (owaspRelatedAlerts.length === 0) {
              console.log("No OWASP-related alerts found.");
            } else {
              console.log(`${owaspRelatedAlerts.length} OWASP-related alerts found.`);
              owaspRelatedAlerts.forEach(alert => {
                console.log(`Annotating Alert: ${alert.rule.description} (Severity: ${alert.rule.security_severity_level})`);
                
                // Annotate or add comment on OWASP-related alerts
                github.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: alert.number,
                  body: `This alert is related to OWASP Top 10: ${alert.rule.description}`
                });
              });
            }

            return owaspRelatedAlerts;
